"""PKCE (RFC 7636) parameter generation for archprime-cli premium login.

PKCE = Proof Key for Code Exchange. Used to authenticate a CLI/native app
without storing client secrets:
- Generate random `code_verifier` (43-128 chars, URL-safe)
- Compute `code_challenge` = base64url(SHA-256(code_verifier))
- Send challenge to authorization server in initial request
- Send verifier later when exchanging code for tokens
- Server validates SHA-256(verifier) == challenge before issuing tokens

Why: a CLI cannot keep a client_secret confidential (it's bundled in the
distribution). PKCE replaces that with a per-session ephemeral secret.
"""
from __future__ import annotations

import base64
import hashlib
import secrets
from dataclasses import dataclass


def _b64url(data: bytes) -> str:
    """Encode bytes as base64url (no padding)."""
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


@dataclass(frozen=True)
class PkceParams:
    """PKCE parameters generated by the CLI for a single login attempt."""

    code_verifier: str
    code_challenge: str
    state: str

    @classmethod
    def generate(cls) -> PkceParams:
        """Generate a fresh PKCE param set per RFC 7636.

        - code_verifier: 64 random URL-safe bytes → ~86 chars (within 43-128 spec)
        - code_challenge: base64url(SHA-256(verifier))
        - state: 24 random URL-safe bytes for CSRF protection (~32 chars)
        """
        verifier = secrets.token_urlsafe(64)
        verifier_bytes = verifier.encode("ascii")
        challenge_digest = hashlib.sha256(verifier_bytes).digest()
        challenge = _b64url(challenge_digest)
        state = secrets.token_urlsafe(24)
        return cls(
            code_verifier=verifier,
            code_challenge=challenge,
            state=state,
        )

    @property
    def code_challenge_method(self) -> str:
        """RFC 7636 challenge method identifier — always SHA-256 here."""
        return "S256"
